# -*- coding: utf-8 -*-
"""indian_stock_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nj41b-9JOspwj0uK5-BY898qimCwIUqd
"""

!pip install yfinance pandas streamlit sqlalchemy

#Imports
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
import os

# Indian stocks on NSE
stocks = ["RELIANCE.NS", "TCS.NS" , "INFY.NS", "HDFCBANK.NS", "WIPRO.NS"]
DATA_PATH = "data/raw_stock_data.csv"
print(DATA_PATH)
os.makedirs("data", exist_ok=True)

#fetch data

if os.path.exists(DATA_PATH):
    print("📂 Loading data from CSV...")
    data = pd.read_csv(DATA_PATH, index_col=0, parse_dates=True)
else:
    print("🌐 Fetching data from yfinance...")
    data = yf.download(stocks, period="3mo", interval="1d")["Close"]
    data.to_csv(DATA_PATH)
    print(" Data fetched and saved!")

from sklearn.metrics import mean_absolute_error

def predict_stock(data, stock_name):

    print(f"\n🔍 Processing {stock_name}...")

    # Step 1: Prepare data
    stock_data = data[[stock_name]].copy()
    stock_data = stock_data.dropna()
    stock_data.rename(columns={stock_name: "Close"}, inplace=True)

    # Step 2: Feature Engineering (UPGRADED)
    stock_data["Days"] = range(len(stock_data))
    stock_data["Returns"] = stock_data["Close"].pct_change()
    stock_data["MA_5"] = stock_data["Close"].rolling(5).mean()
    stock_data["MA_10"] = stock_data["Close"].rolling(10).mean()

    stock_data = stock_data.dropna()

    # Step 3: Prepare ML data (MULTIPLE FEATURES)
    X = stock_data[["Days", "MA_5", "MA_10", "Returns"]]
    y = stock_data["Close"]

    # Step 4: Train model
    model = LinearRegression()
    model.fit(X, y)

    # Step 5: Evaluate model (NEW 🔥)
    y_pred = model.predict(X)
    mae = mean_absolute_error(y, y_pred)
    print(f"📊 Model MAE: {mae:.2f}")

    # Step 6: Predict next 7 days
    last_day = stock_data["Days"].iloc[-1]
    last_ma5 = stock_data["MA_5"].iloc[-1]
    last_ma10 = stock_data["MA_10"].iloc[-1]
    last_return = stock_data["Returns"].iloc[-1]

    future_data = pd.DataFrame({
        "Days": [last_day + i for i in range(1, 8)],
        "MA_5": [last_ma5]*7,
        "MA_10": [last_ma10]*7,
        "Returns": [last_return]*7
    })

    predictions = model.predict(future_data)

    # Step 7: Save processed data
    stock_data.to_csv(f"data/{stock_name}_processed.csv", index=False)

    pred_df = pd.DataFrame({
        "Day": range(1, 8),
        "Predicted Price": predictions
    })
    pred_df.to_csv(f"data/{stock_name}_predictions.csv", index=False)

    # Step 8: Plot
    plt.figure(figsize=(10, 5))

    plt.plot(stock_data["Days"], stock_data["Close"], label="Actual Price")

    plt.plot(
        range(last_day + 1, last_day + 8),
        predictions,
        linestyle="--",
        label="Predicted Price"
    )

    plt.title(f"{stock_name} Price Prediction")
    plt.xlabel("Days")
    plt.ylabel("Price (INR ₹)")
    plt.legend()
    plt.grid(True)
    plt.show()

    # Step 9: Print predictions
    print(f"\n📈 {stock_name} Next 7 Days Prediction:")
    for i, price in enumerate(predictions, 1):
        print(f"Day {i}: ₹{price:.2f}")

# Call the prediction function for each stock
for stock_name in stocks:
    predict_stock(data, stock_name)