# -*- coding: utf-8 -*-
"""sentiment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uc6Y_fqGghEF4PlQz6TdKVXJonwbF8d2
"""



from textblob import TextBlob

def analyze_sentiment(news_list):
    results = []

    for news in news_list:
        polarity = TextBlob(news).sentiment.polarity

        if polarity > 0:
            sentiment = "Positive"
        elif polarity < 0:
            sentiment = "Negative"
        else:
            sentiment = "Neutral"

        results.append((news, sentiment))

    return results